name: Generate All OS Distributions

# TODO don't copy other workflows, run them from this event via https://github.com/peter-evans/repository-dispatch

on: workflow_dispatch # manually triggered

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Install WiX Toolset
        run: choco install wixtoolset
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Package AIJ
        run: ./gradlew packageAijForWindows_x86 packageAijForWindows_arm
      - uses: actions/upload-artifact@v2
        with:
          name: Windows (x86) Installer (.exe)
          path: build/distributions/*x86*.exe
      - uses: actions/upload-artifact@v2
        with:
          name: Windows (x86) package (.zip)
          path: build/distributions/*x86*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: Windows (Arm) Installer (.exe)
          path: build/distributions/*arm*.exe
      - uses: actions/upload-artifact@v2
        with:
          name: Windows (Arm) package (.zip)
          path: build/distributions/*arm*.exe
  linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Package AIJ
        run: ./gradlew packageAijForLinux_x86
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Compressed tar file (.tar.gz)
          path: build/distributions/*x86*.tar.gz #TODO once installer generation is added, gen and upload installers
  macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Make Common Files
        run: ./gradlew commonFiles
      - name: Make ini writable I hope
        run: chmod u=rwx build/commonFiles/AstroImageJ.l4j.ini
      - name: Package AIJ
        run: ./gradlew packageAijForMacos_x86 packageAijForMacos_arm
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS x86 App Version (.zip)
          path: build/distributions/*x86*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS Arm App Version (.zip)
          path: build/distributions/*arm*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS Arm App Version (.dmg)
          path: build/distributions/*arm*.dmg
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS x86 Dmg Version (.dmg)
          path: build/distributions/*x86*.dmg

