# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate Mac Distribution

on: workflow_dispatch # manually triggered
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Make ini writable I hope
        run: chmod u=rwx build/commonFiles/AstroImageJ.l4j.ini
      - name: Package AIJ
        run: ./gradlew packageAijForMacos_x86 packageAijForMacos_arm
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS x86 App Version (.zip)
          path: build/distributions/AstroImageJ-x86_64-mac.zip
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS Arm App Version (.zip)
          path: build/distributions/AstroImageJ-arm_64-mac.zip
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS Arm App Version (.dmg)
          path: build/distributions/AstroImageJ-arm_64-mac.dmg
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS x86 Dmg Version (.dmg)
          path: build/distributions/AstroImageJ-x86_64.dmg
