# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate Mac Distribution

on: workflow_dispatch # manually triggered
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Make Common Files
      run: ./gradlew commonFiles
    - name: Make ini writable I hope
      run: chmod u=rwx build/commonFiles/AstroImageJ.l4j.ini
    - name: Unzip JREs
      run: ./gradlew unZipJresTask
    - name: Build AIJ
      run: ./gradlew build
    - name: Package AIJ
      run: ./gradlew packageAijForMac
    - uses: actions/upload-artifact@v2
      with:
        name: App Version
        path: build/distributions/AstroImageJ-dev-x86-mac.zip
    - uses: actions/upload-artifact@v2
      with:
        name: Dmg Version
        path: build/distributions/AstroImageJ_dev-x86.dmg
